### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by moritz89** [daniel-lewis-ab/litegraph.js#7]
Hi, wanted to ask if you are interested in publishing this forked library in its own NPM package? I forked lightgraph myself, mainly to have up-to-date NPM packages and also implemented a _release-it_ flow to simplify building and publishing the package.

Have a look at the [README](https://github.com/InamataCo/litegraph.js) and [package.json](https://github.com/InamataCo/litegraph.js/blob/master/package.json).

**Comment by daniel-lewis-ab** [comment]
Yeah, sure.  That probably makes sense.

**Comment by daniel-lewis-ab** [comment]
![image](https://github.com/daniel-lewis-ab/litegraph.js/assets/12051895/d00d76a9-931c-4b9d-9b2f-01938b2ab7e4)

**Comment by daniel-lewis-ab** [comment]
Currently building bugfix version updates automatically.  Will integrate minor/major later.
